### ISSUE TITLE
Handle GIT conflicts

### ISSUE THREAD

**Issue by alexszilagyi** [gocom/git-draft#6]
### Prerequisites

* [x] Are you running the latest version of git-draft? Yes

### Expected behaviour

I would expect to handle the conflicts as well, for example to be able to specify to use all incoming changes and override them.
If I get one commit with conflicts taken from that cherry-pick, then after solving the conflicts and committing the changes to the branch and specifying: `Skip and continue from the next commit (Yes/no)? Yes` should go to the next cherry pick and if there is a conflict to wait until I solve the conflicts, merge them and Specify again to skip.

### Actual behaviour

If I have a cherry pick which has some conflicts then the skip functionality does not work since it throws me an error:
```
Skip and continue from the next commit (Yes/no)? Yes
error: no cherry-pick or revert in progress
fatal: cherry-pick failed
✘ Aborting cherry-pick failed
```

### Steps to reproduce

1.  `git draft dev JIRA-1223 JIRA-2323 --all`
2.  Have a GIT conflict, solve it and commit to your branch
3. Type: `Yes` and hit `ENTER` or `RETURN` to the keyboard
4. You would see the following error:
```
Skip and continue from the next commit (Yes/no)? Yes
error: no cherry-pick or revert in progress
fatal: cherry-pick failed
✘ Aborting cherry-pick failed
```

#### Additional information

* Operating system (`$ uname -a`): `Darwin Alexs-MacBook-Pro-14.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020 arm64` 
* git version (`$ git --version`): `git version 2.39.2 (Apple Git-143)`
* bash version (`$ bash --version`): 
```
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)
Copyright (C) 2007 Free Software Foundation, Inc.
```
* git-draft version (`$ git-draft --version`): 0.2.0

**Comment by gocom** [comment]
The current opinionated workflow expects that one would answer no to the conflict prompt, leaving the revert in progress, allowing it to be resolved. Once the conflict has been resolved, the git-draft command can be ran again (without `--all` flag so that it skips already cherry-picked commits).

Answering yes to the prompt will currently run abort to the revert/cherry-pick, which in this case would fail due to there no longer being any on-going revert or cherry-pick. Yes option is intended to use cases where conflicting reverts/cherry-picks are handled last, or where the commit is skipped altogether due to dependencies to other commits/changes that can not be included in the changeset/release.

I may at some point look into expanding the yes option to check whether there is on going cherry-pick or revert in progress, and if there is not, skip the abort. Or by adding third option to the prompt, which might be safer option.
